nguage: objective-c
before_install:
    - pod install
script:
  - xctool test -workspace TOS.xcworkspace -scheme TOSTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - cd $TRAVIS_BUILD_DIR && slather
